### PR TITLE
feat: add name in bentorequest spec

### PR DESCRIPTION
**Pull request by FogDong**

### CODE REVIEW

**Comment by yetone** [comment]
‌‌What does this `name` field mean? Can it be replaced with the `name` of `CR`? It feels like these two fields are redundant.

**Comment by FogDong** [comment]
it can not be replaced with the name of CR. In fact, it is the name of entry service. In the past, the entry service can only be `apiserver`, but now it need a name.

**Comment by yetone** [comment]
‌‌‌‌Generally, a `CRD` should not have a `name` field because it duplicates the `name` in the `metadata`. Having two `name` fields can confuse the creator of the `CR`. This seems more appropriately called an `entryServiceName`. However, a new question arises: why does the `bentoRequest` `CRD` need an 'entryServiceName' field?

**Comment by FogDong** [comment]
I agree that the naming is kinda confusing.

In yatai-serverless, the controller needs to use the name to make some default envs. And bentorequest can pass the name to bento.
https://github.com/bentoml/yatai-serverless/pull/88/files#diff-b9193ab43b3ea7d55f919955bdf2c1881bce97550f706191e2d464a1aad8af14R2177

Or maybe we can deprecate the default env in yatai-serverless and make it in bentocloud to keep the CRD & controller more clean.

**Pull request closed without merging**
